name: space-shooter
on:
  schedule:
    - cron: '0 9 * * 1'
jobs:
  space-shooter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Space Shooter
        uses: github-space-shooter